### ISSUE TITLE
Change site logo

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#1]
please use the attached file for the site logo

[attach the file]

**Comment by PereiraATXFoto** [comment]
resolved by [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/3a669e933321c48698b1b6c683dce495c68f78c0)

**Comment by PresidentNick** [comment]
I made the background on the logo transparent and I added the logo to the header and the footer
