### ISSUE TITLE
Album Tab

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#10]
I would like the Album tab to open up with - 'Polaroid-style' and within the images when clicked on the polaroid "picture" Which will be named for the client I want it to be password protected so only the client is able to see their whole gallery/album. I would like the protected album to be 'Photo Album' style

**Comment by PresidentNick** [comment]
I added the polaroid style albums page but will leave the second part pending until we have albums to add

**Comment by PereiraATXFoto** [comment]
Update to:

file:///C:/Users/barba/Downloads/missio-html/template/missio/gallery2.html
