### ISSUE TITLE
Shop tab

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#11]
Under the shop tab, I would like the following from 'Elements' which is the style 'Services with Grid View' under the Services-Images section. When someone clicks on the tab that will be print photos - it will redirect them to my shop (still working on the kinks) and the same goes for the shop for printing photos onto items etc

**Comment by PresidentNick** [comment]
I added the shop tab with [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/a23decdefaeb252a12bab6bf66a0c733b07dd524)
