### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#13]
![8F3D5B03-BD53-492A-91C6-985D36C7ED04](https://user-images.githubusercontent.com/61593422/82127636-c8452380-977a-11ea-8b4f-6dcca6bdaf86.png)

**Comment by PereiraATXFoto** [comment]
![Photo May 16, 5 01 35 PM](https://user-images.githubusercontent.com/61593422/82131084-2d0e7700-9797-11ea-829c-119caea07ffa.png)

**Comment by PresidentNick** [comment]
resolved by [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/955fe1cefe2d1376e8c4bf683b374b2bfb877c89)
