### ISSUE TITLE
Home Page - 1

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#14]
-Keep Carousel photo gallery section
-Keep 'What services do I provide?' section
-Take off 'Featured Wedding' section
-Take off 'Love stories' section
-Take off testimonial that is not the slider one
-Keep 'My story' section
-Update Instagram and Facebook @pereiraatxfoto

**Comment by PresidentNick** [comment]
resolved by [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/44ca17fe83db341fbc2eb68b2ac54c9f9d04baad)
