### ISSUE TITLE
Home Page - Under Services I provide

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#19]
-Graduation Photo
![Davuluri_051719_04](https://user-images.githubusercontent.com/61593422/82157577-e62c8a00-9847-11ea-8034-eb1652239291.jpg)

**Comment by PresidentNick** [comment]
resolved by [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/c9782c4cc06f136bb76205e22f95782a41e8297e)
