### ISSUE TITLE
Pls add Instagram Feed

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#2]
Instagram feed in homepage above the footer.

**Comment by PresidentNick** [comment]
Which version of the instagram feed do you want above the footer? There are three options:

1
![image](https://user-images.githubusercontent.com/8160053/76783303-a4b42b80-677f-11ea-8e16-822e05214ef7.png)


2
![image](https://user-images.githubusercontent.com/8160053/76783332-b3024780-677f-11ea-92b2-3dcce86b3312.png)


3 
![image](https://user-images.githubusercontent.com/8160053/76783371-c2819080-677f-11ea-9c9d-fac15ad1a337.png)

**Comment by PereiraATXFoto** [comment]
Option 1

**Comment by PresidentNick** [comment]
Do you want the header, subheader above the images, and the button below the images? If so, what should the header, subheader, and button text be and where should the button go to (your instagram page)? Or do you only want the images? As far as the images go, I think it's going to load the 6 latest images from your instagram, does that work for this element? Or do you want it to load specific images?

**Comment by PereiraATXFoto** [comment]
Option 1 and just leave the button. The button I want it to say "Follow on Instagram @pereira.atxfotografia" and it links to the Instagram page.

**Comment by PresidentNick** [comment]
Resolved with [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/96803f889e218f52d680a1cab3879a5e342df6ff). Ready for review on live site
