### ISSUE TITLE
Home Page - Under service I provide

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#20]
-Pets

**Comment by PereiraATXFoto** [comment]
![DSC_8673](https://user-images.githubusercontent.com/61593422/82157621-2ee44300-9848-11ea-9016-9a6dc6acd93e.jpg)

**Comment by PresidentNick** [comment]
resolved by [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/c9782c4cc06f136bb76205e22f95782a41e8297e)
