### ISSUE TITLE
Home Page Tabs

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#4]
I want the following tabs for the homepage

-Home
-Portfolio
-Community Involvement
-Albums
-Pricing
-About Me
-Contact

**Comment by PresidentNick** [comment]
I've updated the tabs with [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/dcf35215eb30a34045ebf0482c1b7bd23ceb85f1), it is ready for review on the live site. Let me know if you want me the change the content of the dropdowns, the style of the dropdowns or remove the dropdowns. There are two dropdown styles. The dropdown for home and the dropdown for portfolio are the two styles. Currently the nav links are not connected to any page, but we can make separate tickets to create the pages required for those nav links, for example the portfolio page will be connected to the portfolio nav link.

**Comment by PereiraATXFoto** [comment]
Please change home page tabs to
-Home
-Gallery
-Albums
-Community Involvement
-Pricing
-Contact

**Comment by PresidentNick** [comment]
I'm going to link the tabs to urls like this:

Home - /
Gallery - /gallery
Albums - /albums
Community Involvement - /community
Pricing - /pricing
Contact - /contact

let me know if those URLs work for you. Do you want any drop-down menus on any of the tabs?

**Comment by PereiraATXFoto** [comment]
Next to Pricing, I want to put shop

It will have the option to shop with a third party vendor for photos, gift cards, and presets

**Comment by PereiraATXFoto** [comment]
No drop down just going straight to the site

**Comment by PresidentNick** [comment]
> Next to Pricing, I want to put shop


Do you want the shop tab to the left or to the right of pricing?

**Comment by PereiraATXFoto** [comment]
right of pricing

**Comment by PresidentNick** [comment]
I've updated the tabs with [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/7dc47feef4303c635d6d1f9a077619e0f1cdacde), and it is ready for review on the live site.

**Comment by PresidentNick** [comment]
After reviewing, comment here about any issues if you need more changes. If my commit works for you, you can close this issue to signify my commit resolves this issue.

**Comment by PresidentNick** [comment]
Actually I think it'll work better to do the other way around. I will close the issue if I think I met all the requirements. After reviewing, if you notice I haven't met all the requirements, reopen this issue and comment on what needs to be changed.
