### ISSUE TITLE
Gallery Instead of Portfolio

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#5]
I would like to have just a Gallery instead of portfolio since it is the same thing in my perspective. Option: Lightbox - Three Column Grid

**Comment by PresidentNick** [comment]
Resolved with [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/8a768b5ec870027af5d4853d03f81183a767e057), ready to review on live site
