### ISSUE TITLE
Add Albums Next to Gallery

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#6]
This will be the area in which customers will be able to see their albums and download their photos or be redirected to a third party site to print them.

**Comment by PresidentNick** [comment]
Do you want Albums added to the right or to the left of Gallery on the nav?

**Comment by PereiraATXFoto** [comment]
The way it is right now is perfect

**Comment by PresidentNick** [comment]
Ok, I'm going to close this ticket
