### ISSUE TITLE
Testimonial

### ISSUE THREAD

**Issue by PereiraATXFoto** [PereiraATXFoto/pereiraatxfoto.github.io#7]
I would like to add testimonials in the very first page at the bottom

Testimonials Slider - Alternative

**Comment by PresidentNick** [comment]
Do you want this between the instagram gallery and the footer?

**Comment by PereiraATXFoto** [comment]
No instagram Gallery, leave the footer

**Comment by PresidentNick** [comment]
Resolved by [this commit](https://github.com/PereiraATXFoto/pereiraatxfoto.github.io/commit/7030abc2ccaf0479d3b8457ba55ed446377f09cfl)
